##  Milestone1

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

## Load Data

In [3]:
data=pd.read_csv('flights.csv')
data.head(5)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

## Data Understanding

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB

In [5]:
data.columns

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
       'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
       'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
       'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'],
      dtype='object')

In [6]:
data.describe()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
count,5819079.0,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.732926e+06,5.732926e+06,5.730032e+06,5.730032e+06,...,5.819079e+06,5.726566e+06,5.714008e+06,5.819079e+06,5.819079e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06
mean,2015.0,6.524085e+00,1.570459e+01,3.926941e+00,2.173093e+03,1.329602e+03,1.335204e+03,9.370158e+00,1.607166e+01,1.357171e+03,...,1.493808e+03,1.476491e+03,4.407057e+00,2.609863e-03,1.544643e-02,1.348057e+01,7.615387e-02,1.896955e+01,2.347284e+01,2.915290e+00
std,0.0,3.405137e+00,8.783425e+00,1.988845e+00,1.757064e+03,4.837518e+02,4.964233e+02,3.708094e+01,8.895574e+00,4.980094e+02,...,5.071647e+02,5.263197e+02,3.927130e+01,5.102012e-02,1.233201e-01,2.800368e+01,2.143460e+00,4.816164e+01,4.319702e+01,2.043334e+01
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.200000e+01,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,-8.700000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2015.0,4.000000e+00,8.000000e+00,2.000000e+00,7.300000e+02,9.170000e+02,9.210000e+02,-5.000000e+00,1.100000e+01,9.350000e+02,...,1.110000e+03,1.059000e+03,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2015.0,7.000000e+00,1.600000e+01,4.000000e+00,1.690000e+03,1.325000e+03,1.330000e+03,-2.000000e+00,1.400000e+01,1.343000e+03,...,1.520000e+03,1.512000e+03,-5.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,3.000000e+00,0.000000e+00
75%,2015.0,9.000000e+00,2.300000e+01,6.000000e+00,3.230000e+03,1.730000e+03,1.740000e+03,7.000000e+00,1.900000e+01,1.754000e+03,...,1.918000e+03,1.917000e+03,8.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,1.900000e+01,2.900000e+01,0.000000e+00
max,2015.0,1.200000e+01,3.100000e+01,7.000000e+00,9.855000e+03,2.359000e+03,2.400000e+03,1.988000e+03,2.250000e+02,2.400000e+03,...,2.400000e+03,2.400000e+03,1.971000e+03,1.000000e+00,1.000000e+00,1.134000e+03,5.730000e+02,1.971000e+03,1.331000e+03,1.211000e+03

In [7]:
data.shape

(5819079, 31)

In [29]:
data.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
TAXI_OUT                 89047
WHEELS_OFF               89047
SCHEDULED_TIME               6
ELAPSED_TIME            105071
AIR_TIME                105071
DISTANCE                     0
WHEELS_ON                92513
TAXI_IN                  92513
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

## Derive Route column

In [5]:
data['ROUTE'] = (
    data['ORIGIN_AIRPORT'].astype(str)
    + '_'
    + data['DESTINATION_AIRPORT'].astype(str)
)

In [6]:
data['ROUTE']

0          ANC_SEA
1          LAX_PBI
2          SFO_CLT
3          LAX_MIA
4          SEA_ANC
            ...
5819074    LAX_BOS
5819075    JFK_PSE
5819076    JFK_SJU
5819077    MCO_SJU
5819078    JFK_BQN
Name: ROUTE, Length: 5819079, dtype: object

month_order = [
 'January','February','March','April','May','June',
 'July','August','September','October','November','December'
]

data['MONTH'] = pd.Categorical(
    data['MONTH'],
    categories=month_order,
    ordered=True
)

# Step 3: Now safely convert MONTH to named categorical
month_map = {1:'January', 2:'February', 3:'March', 4:'April',
             5:'May', 6:'June', 7:'July', 8:'August',
             9:'September', 10:'October', 11:'November', 12:'December'}

month_order = ['January','February','March','April','May','June',
               'July','August','September','October','November','December']

data['MONTH'] = pd.Categorical(data['MONTH'].map(month_map), 
                                categories=month_order, ordered=True)

# Step 4: Map DAY_OF_WEEK
day_map = {1:'Monday', 2:'Tuesday', 3:'Wednesday', 4:'Thursday',
           5:'Friday', 6:'Saturday', 7:'Sunday'}
data['DAY_OF_WEEK'] = data['DAY_OF_WEEK'].map(day_map)

# Verify
print(data['MONTH'].head())
print(data['FLIGHT_DATE'].head())

In [76]:
day_map = {
    1: 'Monday',2: 'Tuesday',
    3: 'Wednesday',4: 'Thursday',
    5: 'Friday',6: 'Saturday', 7: 'Sunday'
}

data['DAY_OF_WEEK'] = data['DAY_OF_WEEK'].map(day_map)

print(data['MONTH'].dtype)
print(data['MONTH'].head(10))
print(data['YEAR'].head(5))
print(data['DAY'].head(5))

data['MONTH'].unique

## Preprocess cancellation reason column

In [81]:
data['CANCELLATION_REASON'].unique()

array([nan, 'A', 'B', 'C', 'D'], dtype=object)

In [83]:
data['CANCELLATION_REASON'].count()

89884

In [11]:
data['CANCELLATION_REASON'].value_counts(dropna=False)

CANCELLATION_REASON
NaN    5729195
B        48851
A        25262
C        15749
D           22
Name: count, dtype: int64

In [89]:
data['CANCELLED'].value_counts()

CANCELLED
0    5729195
1      89884
Name: count, dtype: int64

In [13]:
result = data.loc[
    data['CANCELLED'] == 0,
    ['CANCELLED', 'CANCELLATION_REASON']
]
result

         CANCELLED CANCELLATION_REASON
0                0                 NaN
1                0                 NaN
2                0                 NaN
3                0                 NaN
4                0                 NaN
...            ...                 ...
5819074          0                 NaN
5819075          0                 NaN
5819076          0                 NaN
5819077          0                 NaN
5819078          0                 NaN

[5729195 rows x 2 columns]

In [15]:
result = data.loc[
    data['CANCELLED'] == 1,
    ['CANCELLED', 'CANCELLATION_REASON']
]
result

         CANCELLED CANCELLATION_REASON
32               1                   A
42               1                   B
68               1                   B
82               1                   B
90               1                   A
...            ...                 ...
5818090          1                   A
5818157          1                   A
5818318          1                   A
5818777          1                   A
5818843          1                   A

[89884 rows x 2 columns]

In [17]:
data['CANCELLATION_REASON']=data['CANCELLATION_REASON'].replace("A","Airline/Carrier")
data['CANCELLATION_REASON']=data['CANCELLATION_REASON'].replace("B","Weather")
data['CANCELLATION_REASON']=data['CANCELLATION_REASON'].replace("C","National Aviation System")
data['CANCELLATION_REASON']=data['CANCELLATION_REASON'].replace("D","Security")

In [19]:
data['CANCELLATION_REASON']=data['CANCELLATION_REASON'].fillna("Not Cancelled")

In [21]:
data['CANCELLATION_REASON'].isnull().sum()

0

## Format Date time columns

In [23]:
data['FLIGHT_DATE'] = pd.to_datetime(data[['YEAR','MONTH','DAY']])

In [25]:
data['FLIGHT_DATE']

0         2015-01-01
1         2015-01-01
2         2015-01-01
3         2015-01-01
4         2015-01-01
             ...
5819074   2015-12-31
5819075   2015-12-31
5819076   2015-12-31
5819077   2015-12-31
5819078   2015-12-31
Name: FLIGHT_DATE, Length: 5819079, dtype: datetime64[ns]

In [30]:
cols = [
    'SCHEDULED_DEPARTURE',
    'DEPARTURE_TIME',
    'SCHEDULED_ARRIVAL',
    'ARRIVAL_TIME'
]

for c in cols:

    hhmm = data[c].astype('Int64').astype(str).str.zfill(4)

    time_str = hhmm.str[:2] + ':' + hhmm.str[2:]

    data[c + '_DT'] = pd.to_datetime(
        data['FLIGHT_DATE'].astype(str) + ' ' + time_str,
        errors='coerce'
    )

In [106]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 37 columns):
 #   Column                  Dtype
---  ------                  -----
 0   YEAR                    int64
 1   MONTH                   int64
 2   DAY                     int64
 3   DAY_OF_WEEK             object
 4   AIRLINE                 object
 5   FLIGHT_NUMBER           int64
 6   TAIL_NUMBER             object
 7   ORIGIN_AIRPORT          object
 8   DESTINATION_AIRPORT     object
 9   SCHEDULED_DEPARTURE     int64
 10  DEPARTURE_TIME          float64
 11  DEPARTURE_DELAY         float64
 12  TAXI_OUT                float64
 13  WHEELS_OFF              float64
 14  SCHEDULED_TIME          float64
 15  ELAPSED_TIME            float64
 16  AIR_TIME                float64
 17  DISTANCE                int64
 18  WHEELS_ON               float64
 19  TAXI_IN                 float64
 20  SCHEDULED_ARRIVAL       int64
 21  ARRIVAL_TIME            float64
 22  ARRIVAL_DELAY           float64
 23  DIVERTED                int64
 24  CANCELLED               int64
 25  CANCELLATION_REASON     object
 26  AIR_SYSTEM_DELAY        float64
 27  SECURITY_DELAY          float64
 28  AIRLINE_DELAY           float64
 29  LATE_AIRCRAFT_DELAY     float64
 30  WEATHER_DELAY           float64
 31  ROUTE                   object
 32  FLIGHT_DATE             datetime64[ns]
 33  SCHEDULED_DEPARTURE_DT  datetime64[ns]
 34  DEPARTURE_TIME_DT       datetime64[ns]
 35  SCHEDULED_ARRIVAL_DT    datetime64[ns]
 36  ARRIVAL_TIME_DT         datetime64[ns]
dtypes: datetime64[ns](5), float64(16), int64(9), object(7)
memory usage: 1.6+ GB

In [31]:
data['SCHEDULED_ARRIVAL_DT']

0         2015-01-01 04:30:00
1         2015-01-01 07:50:00
2         2015-01-01 08:06:00
3         2015-01-01 08:05:00
4         2015-01-01 03:20:00
                  ...
5819074   2015-12-31 08:19:00
5819075   2015-12-31 04:46:00
5819076   2015-12-31 04:40:00
5819077   2015-12-31 03:40:00
5819078   2015-12-31 04:40:00
Name: SCHEDULED_ARRIVAL_DT, Length: 5819079, dtype: datetime64[ns]

## Handling Null values in Delay columns

In [108]:
data.isnull().sum()

YEAR                            0
MONTH                           0
DAY                             0
DAY_OF_WEEK                     0
AIRLINE                         0
FLIGHT_NUMBER                   0
TAIL_NUMBER                 14721
ORIGIN_AIRPORT                  0
DESTINATION_AIRPORT             0
SCHEDULED_DEPARTURE             0
DEPARTURE_TIME              86153
DEPARTURE_DELAY             86153
TAXI_OUT                    89047
WHEELS_OFF                  89047
SCHEDULED_TIME                  6
ELAPSED_TIME               105071
AIR_TIME                   105071
DISTANCE                        0
WHEELS_ON                   92513
TAXI_IN                     92513
SCHEDULED_ARRIVAL               0
ARRIVAL_TIME                92513
ARRIVAL_DELAY              105071
DIVERTED                        0
CANCELLED                       0
CANCELLATION_REASON             0
AIR_SYSTEM_DELAY          4755640
SECURITY_DELAY            4755640
AIRLINE_DELAY             4755640
LATE_AIRCRAFT_DELAY       4755640
WEATHER_DELAY             4755640
ROUTE                           0
FLIGHT_DATE                     0
SCHEDULED_DEPARTURE_DT          0
DEPARTURE_TIME_DT           86666
SCHEDULED_ARRIVAL_DT            2
ARRIVAL_TIME_DT             94969
dtype: int64

In [32]:
data['AIRLINE_DELAY'].value_counts()

AIRLINE_DELAY
0.0       493417
1.0        21319
2.0        21211
3.0        20656
4.0        20184
           ...
965.0          1
1160.0         1
918.0          1
823.0          1
1636.0         1
Name: count, Length: 1067, dtype: int64

In [53]:
data['AIRLINE_DELAY'].isnull().sum()

4755640

In [33]:
cause_cols = [
    'AIRLINE_DELAY','WEATHER_DELAY','AIR_SYSTEM_DELAY',
    'SECURITY_DELAY','LATE_AIRCRAFT_DELAY'
]

In [34]:
data.loc[
    (data['DIVERTED'] == 1) | (data['CANCELLED'] == 1),
    ['ARRIVAL_DELAY', 'DEPARTURE_DELAY', 'DIVERTED', 'CANCELLED'] + cause_cols
]

,ARRIVAL_DELAY,DEPARTURE_DELAY,DIVERTED,CANCELLED,AIRLINE_DELAY,WEATHER_DELAY,AIR_SYSTEM_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
32,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
5818157,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN
5818160,NaN,13.0,1,0,NaN,NaN,NaN,NaN,NaN
5818318,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN
5818777,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN
5818843,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN

In [111]:
data['CANCELLED'].value_counts()

CANCELLED
0    5729195
1      89884
Name: count, dtype: int64

In [35]:
subset = data.loc[
    data[cause_cols].notna().any(axis=1),
    ['ARRIVAL_DELAY', 'DEPARTURE_DELAY'] + cause_cols
]
subset.head(20)

,ARRIVAL_DELAY,DEPARTURE_DELAY,AIRLINE_DELAY,WEATHER_DELAY,AIR_SYSTEM_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
27,25.0,12.0,0.0,0.0,25.0,0.0,0.0
30,43.0,72.0,0.0,0.0,43.0,0.0,0.0
35,15.0,0.0,15.0,0.0,0.0,0.0,0.0
50,20.0,-3.0,0.0,0.0,20.0,0.0,0.0
52,85.0,95.0,85.0,0.0,0.0,0.0,0.0
55,89.0,72.0,72.0,0.0,17.0,0.0,0.0
70,102.0,108.0,0.0,102.0,0.0,0.0,0.0
73,60.0,60.0,60.0,0.0,0.0,0.0,0.0
74,54.0,58.0,54.0,0.0,0.0,0.0,0.0
86,66.0,53.0,53.0,0.0,13.0,0.0,0.0
92,26.0,19.0,19.0,0.0,7.0,0.0,0.0
97,19.0,43.0,19.0,0.0,0.0,0.0,0.0
102,78.0,56.0,56.0,0.0,22.0,0.0,0.0
106,128.0,148.0,0.0,128.0,0.0,0.0,0.0
111,25.0,-2.0,0.0,0.0,25.0,0.0,0.0
120,69.0,55.0,55.0,0.0,14.0,0.0,0.0
126,17.0,36.0,17.0,0.0,0.0,0.0,0.0
129,56.0,73.0,56.0,0.0,0.0,0.0,0.0
137,43.0,39.0,39.0,0.0,4.0,0.0,0.0
149,20.0,6.0,6.0,0.0,14.0,0.0,0.0

 - if arrival_delay is  < 0 then flight is on time

In [36]:
data[cause_cols] = data[cause_cols].fillna(0)

In [37]:
data[['AIRLINE_DELAY',
    'WEATHER_DELAY',
    'AIR_SYSTEM_DELAY',
    'SECURITY_DELAY',
    'LATE_AIRCRAFT_DELAY']].isnull().sum()

AIRLINE_DELAY          0
WEATHER_DELAY          0
AIR_SYSTEM_DELAY       0
SECURITY_DELAY         0
LATE_AIRCRAFT_DELAY    0
dtype: int64

In [116]:
data.isnull().sum()

YEAR                           0
MONTH                          0
DAY                            0
DAY_OF_WEEK                    0
AIRLINE                        0
FLIGHT_NUMBER                  0
TAIL_NUMBER                14721
ORIGIN_AIRPORT                 0
DESTINATION_AIRPORT            0
SCHEDULED_DEPARTURE            0
DEPARTURE_TIME             86153
DEPARTURE_DELAY            86153
TAXI_OUT                   89047
WHEELS_OFF                 89047
SCHEDULED_TIME                 6
ELAPSED_TIME              105071
AIR_TIME                  105071
DISTANCE                       0
WHEELS_ON                  92513
TAXI_IN                    92513
SCHEDULED_ARRIVAL              0
ARRIVAL_TIME               92513
ARRIVAL_DELAY             105071
DIVERTED                       0
CANCELLED                      0
CANCELLATION_REASON            0
AIR_SYSTEM_DELAY               0
SECURITY_DELAY                 0
AIRLINE_DELAY                  0
LATE_AIRCRAFT_DELAY            0
WEATHER_DELAY                  0
ROUTE                          0
FLIGHT_DATE                    0
SCHEDULED_DEPARTURE_DT         0
DEPARTURE_TIME_DT          86666
SCHEDULED_ARRIVAL_DT           2
ARRIVAL_TIME_DT            94969
dtype: int64

## Drop Irrelavent columns

In [38]:
data.drop(['TAIL_NUMBER','FLIGHT_NUMBER','SCHEDULED_DEPARTURE','DEPARTURE_TIME','SCHEDULED_ARRIVAL','ARRIVAL_TIME'],axis=1,inplace=True)

## Memory optimization

In [39]:
## Downcast integer columns
int_cols = data.select_dtypes(include=['int64']).columns

for c in int_cols:
    data[c] = pd.to_numeric(data[c], downcast='integer')

In [40]:
## Downcast Float columns 
float_cols = data.select_dtypes(include=['float64']).columns

for c in float_cols:
    data[c] = pd.to_numeric(data[c], downcast='float')

In [41]:
cat_cols=['CANCELLATION_REASON','ROUTE']
for c in cat_cols:
    if c in data.columns:
        data[c] = data[c].astype('category')

## Save preprocessed Data

In [52]:
import pandas as pd

# Read the broken CSV
df = pd.read_csv('airline_preprocessed.csv', quoting=3)  


print(df.shape)
print(df.columns.tolist())


df.to_csv('airline_preprocessed_fixed.csv', index=False)
print("Done!")

(5819079, 31)
['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'DEPARTURE_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'WHEELS_ON', 'TAXI_IN', 'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON', 'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY', 'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY', 'ROUTE', 'FLIGHT_DATE', 'SCHEDULED_DEPARTURE_DT', 'DEPARTURE_TIME_DT', 'SCHEDULED_ARRIVAL_DT', 'ARRIVAL_TIME_DT']
Done!